version: '3'
services:
  eventstore-node1:
    image: eventstore/eventstore:latest
    ports:
      - 2113:2113
      - 1113:1113
    environment:
      - EVENTSTORE_CLUSTER_SIZE=3
      - EVENTSTORE_CLUSTER_DNS=192.168.3.16,192.168.3.17,192.168.3.18
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    volumes:
      - ./data/data:/var/lib/eventstore
      - ./data/logs:/var/log/eventstore
